FROM maven:3.8.8-eclipse-temurin-21-alpine AS build

WORKDIR /app
COPY . .

ARG NOTION_API_KEY
ENV NOTION_API_KEY=${NOTION_API_KEY}

ARG DATABASE_ID
ENV DATABASE_ID=${DATABASE_ID}

ARG NOTION_VERSION
ENV NOTION_VERSION=${NOTION_VERSION}

ARG CUSTOM_API_KEY
ENV CUSTOM_API_KEY=${CUSTOM_API_KEY}

ARG API_KEY_HEADER
ENV API_KEY_HEADER=${API_KEY_HEADER}

ARG SCORE_DATABASE_ID
ENV SCORE_DATABASE_ID=${SCORE_DATABASE_ID}

ARG CORE_DATABASE_ID
ENV CORE_DATABASE_ID=${CORE_DATABASE_ID}

RUN mvn clean package -DskipTests

FROM amazoncorretto:21.0.3-alpine3.19

COPY --from=build /app/target/notionproxy-0.0.1-SNAPSHOT.jar notion-proxy.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","notion-proxy.jar"]