spring:
  application:
    name: notionproxy
  config:
    import: optional:file:.env[.properties]
  cache:
    jcache:
      config: "classpath:ehcache.xml"
  cloud:
    gcp:
      core:
        enabled: false
      storage:
        enabled: false

server:
  servlet:
    context-path: /

CACHE_EXPIRE_IN_MILLISECONDS: 120000