spring:
  application:
    name: notionproxy
  config:
    import: optional:file:.env[.properties]
  cache:
    jcache:
      config: "classpath:ehcache.xml"

server:
  servlet:
    context-path: /

CACHE_EXPIRE_IN_MILLISECONDS: 604800000