spring:
  application:
    name: notionproxy
  config:
    import: optional:file:.env[.properties]
  data:
    redis:
      host: localhost
      port: 6379
  cache:
      type: redis
      redis:
        time-to-live: 7000
server:
  servlet:
    context-path: /api/

