spring:
  application:
    name: notionproxy
  config:
    import: optional:file:.env[.properties]
  cache:
    jcache:
      config: classpath:ehcache.xml



logging:
  level:
    org.springframework.cache: TRACE
    org.ehcache: TRACE

server:
  servlet:
    context-path: /api/

